name: my_church
description: A comprehensive church management system for connecting and engaging with your congregation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # Core UI and Animation
  auto_size_text: 3.0.0
  flutter_animate: ^4.5.2
  flutter_spinkit: 5.2.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  google_fonts: 6.1.0
  json_path: 0.7.2
  page_transition: 2.1.0

  # Navigation and State Management
  go_router: 12.1.3
  provider: 6.1.1

  # Network and Storage
  cached_network_image: 3.4.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  sqflite: 2.3.3+1

  # Media and UI Components
  carousel_slider: ^5.0.0
  dropdown_button2: 2.3.9
  photo_view: 0.15.0
  youtube_player_flutter: ^8.1.2

  # Utilities
  encrypt: ^5.0.3
  intl: 0.19.0
  path_provider: 2.1.4
  timeago: 3.6.1
  url_launcher: 6.3.0

  # iOS Style Icons
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 4.0.0
  lints: 4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/favicon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/adaptive_foreground_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/Slide1.png
    - assets/images/Slide2.png
    - assets/images/Slide3.png
    - assets/images/avatar.jpg
    - assets/images/MyChurch-Logo-white.png
    - assets/images/upcomingevents.jpg
    - assets/images/book1.jpg
    - assets/images/book2.jpg
    - assets/images/book3.jpg
    - assets/images/book4.jpg
    - assets/images/cd1.jpg
    - assets/images/sermon1.png
    - assets/images/sermons.png
    - assets/images/jobs.png
    - assets/images/otpenvelope.png
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/environment_values/
